# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWorldTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloWorldTest

  target 'HelloWorldTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloWorldTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
